### ISSUE TITLE
After first startup, there are no e-mail templates present in administration for me to change

### ISSUE THREAD

**Issue by MarekHavel** [lukynmatuska/teamwork-sspbrno#3]
and therefore most activities fail on this step in the process of sending you an E-mail.

**Comment by MarekHavel** [comment]
Please add the step 'copy * from emails.sample to emails' to readme.md

**Comment by lukynmatuska** [comment]
Fixed in last commit https://github.com/lukynmatuska/teamwork-sspbrno/commit/2dc0f79c8c13681c807de6b1cfe40b1a524d83f4.
