### ISSUE TITLE
Hierarchy menu not working

### ISSUE THREAD

**Issue by MarekHavel** [lukynmatuska/teamwork-sspbrno#7]
This is what happens after I press the zaměření button:
![image](https://user-images.githubusercontent.com/24763421/117514101-638a6680-af93-11eb-8777-c8b34726b922.png)
it doesn't move you anywhere, a # gets added in the address

**Comment by MarekHavel** [comment]
Nor does it work when importing users lol
![image](https://user-images.githubusercontent.com/24763421/117514477-3ab6a100-af94-11eb-8697-b8f3d1500733.png)

**Comment by lukynmatuska** [comment]
Hi Marek,
thanks for the report. Fixed in commit https://github.com/lukynmatuska/teamwork-sspbrno/commit/2dc0f79c8c13681c807de6b1cfe40b1a524d83f4.
